# Generated by Django 3.2.9 on 2021-11-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('address', models.CharField(default='', max_length=50, unique=True)),
                ('address_number', models.IntegerField(default='')),
                ('postal_code', models.IntegerField(default='')),
                ('security', models.IntegerField(default='')),
                ('proposed_by', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
