# Generated by Django 3.2.9 on 2021-11-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_bikeracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeracks',
            name='players',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bikeracks',
            name='school',
            field=models.CharField(default='', max_length=50),
        ),
    ]
