# Generated by Django 3.2.9 on 2021-12-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_auto_20211129_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BikeRacks',
            new_name='BikeRack',
        ),
    ]
