# Generated by Django 3.2.9 on 2021-12-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_rename_bikeracks_bikerack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikerack',
            old_name='security',
            new_name='rating',
        ),
    ]
