# Generated by Django 4.0 on 2021-12-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_rename_security_bikerack_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerack',
            name='surveilance_efficiency',
            field=models.CharField(choices=[('GREEN', 'GREEN'), ('RED', 'RED'), ('YELLOW', 'YELLOW')], default='RED', max_length=50),
        ),
    ]
