# Generated by Django 4.0 on 2021-12-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_bikerack_surveilance_efficiency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikerack',
            old_name='surveilance_efficiency',
            new_name='surveillance_efficiency',
        ),
    ]
